# Generated by Django 5.2.7 on 2026-06-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cours/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20, verbose_name='Année académique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('type_examen', models.CharField(choices=[('controle', 'Contrôle continu'), ('partiel', 'Examen partiel'), ('final', 'Examen final'), ('rattrapage', 'Rattrapage')], max_length=20, verbose_name='Type')),
                ('date_examen', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée (minutes)')),
                ('salle', models.CharField(blank=True, max_length=100, verbose_name='Salle')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20, verbose_name='Année académique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academics.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['date_examen'],
            },
        ),
        migrations.CreateModel(
            name='TravailDirige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='td/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds', to='academics.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Travail Dirigé (TD)',
                'verbose_name_plural': 'Travaux Dirigés (TD)',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='TravailPratique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='tp/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps', to='academics.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps', to='academics.matiere')),
            ],
            options={
                'verbose_name': 'Travail Pratique (TP)',
                'verbose_name_plural': 'Travaux Pratiques (TP)',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moyenne générale')),
                ('mention', models.CharField(blank=True, max_length=100, verbose_name='Mention')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='academics.etudiant')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-created_at'],
                'unique_together': {('etudiant', 'annee_academique', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20, verbose_name='Année académique')),
                ('semestre', models.CharField(default='S1', max_length=20, verbose_name='Semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.etudiant')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='pedagogy.examen')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.matiere')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('etudiant', 'matiere', 'examen', 'semestre')},
            },
        ),
    ]
