# Generated by Django 5.2.7 on 2026-06-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('pedagogy', '0002_remove_examens_bulletins_add_rendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendudevoir',
            name='date_correction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendudevoir',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendus', to='academics.matiere'),
        ),
        migrations.AlterField(
            model_name='rendudevoir',
            name='corrige_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendus_corriges', to='academics.enseignant'),
        ),
    ]
