# Generated by Django 5.2.7 on 2026-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0003_rendudevoir_date_correction_rendudevoir_matiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travaildirige',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='travailpratique',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
