# Generated by Django 5.2.7 on 2026-06-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academics.faculte'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academics.departement'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academics.filiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academics.filiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='academics.matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academics.niveauetude'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academics.niveauetude'),
        ),
    ]
